// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxiriyaygxjmlfpefjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheGlyaXlheWd4am1sZnBlZmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTA5NjYsImV4cCI6MjA1NzkyNjk2Nn0.22R66jR8UiUUt70HHYJv9QNrN4RK3ecQoMZsFSYk4yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);