
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxfexkdvnnefhmzasdhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4ZmV4a2R2bm5lZmhtemFzZGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTMxNDAsImV4cCI6MjA1NzkyOTE0MH0.9XwJ7ykDpIy4aBlU2P5q_mhOoa8H_ADDHOZ7Z8HqseE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
